config/routes.rb
MPPL::Application.routes.draw do

  
  post "paypal/pledge"

  get "paypal/redirect_to_paypal"
  
  scope "(:locale)", :locale => /en|he|it/ do
  
    resources :widgets do
      collection do
        get :translations
        get :faq
      end

      member do
        get :preview
        get :embed
        get :widget
        get :snippet
        get :snippet_mobile_portrait #320x240
        get :snippet_mobile_landscape #480x320
        get :snippet_small_tablet_portrait #600x800
        get :snippet_small_tablet_landscape #800x600
        get :snippet_tablet_portrait #768x1024
        get :snipppet_tablet_landscape #(1024x768)
      end
    end
    resources :categories
    resources :payment_notifications
    
      resources :offers do
  	    resources :pledges do
          member do
            post :pay
            get :paypal_details
          end
        end 
        resources :payments
  
        collection do
          get :chart
        end
        member do
          get :chart
          get :thankyou
          get :accept_cash
          post :receive_cash
          post :add_follower
          post :remove_follower
          post :contact_us
        end
      end
    
  end
  
  

  match '/:locale' => 'home#index'
  root :to => "home#index"


  
  
  scope "(:locale)", :locale => /en|he|it/ do devise_for :users 
  resources :users, :only => [:show, :index] 
   
  
  match 'my_offers', to: "offers#my", as: :my_offers
  match 'my_pledges', to: "pledges#my", as: :my_pledges

  match 'explore', to: "home#explore", as: :explore

  match 'faq', to: "home#faq", as: :faq

  match 'about', to: "payment_notifications#create", via: :post, as: :old_ipn_listener
  match 'about', to: "home#about", via: :get, as: :about

  match 'privacy', to: "home#privacy-policy", as: :privacy
  match 'terms', to: "home#terms-of-use", as: :terms
  match 'how-it-works', to: "home#how_it_works", as: :how_it_works

  match 'pledges', to: "pledges#all", as: :pledges_all
  match 'payments', to: "payments#all", as: :payments_all

  match 'preapproval_return/:id(/:old_pledge_id)', to: "pledges#preapproval_return", via: :get, as: :preapproval_return
  match 'preapproval_cancel/:id(/:old_pledge_id)', to: "pledges#preapproval_cancel", via: :get, as: :preapproval_cancel
  
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   	@offers = Offer.published.limit(20)
   	#TODO:
   	#active offers
   	#featured offers
   	#fresh offers
   	#hot offers
   	#popular offers
   	#most interesting/shared/discussed
   	#CATEGORIES: concerts, courses, food, tech etc.
  end


   # IMPORTANT: the parent_id of main categories must be setted to 0 or nil.
  def explore
  	@offers = Offer.published.limit(20)
    
    categories = Category.all


    @first_level = []
    categories.each do |cat|
      if cat[:parent_id] == 0 || cat[:parent_id] == nil  #hash
        @first_level.push(id: cat[:id], name: cat[:name], subcategories: [] );
      end
    end


    categories.each do |cat|
      if cat[:parent_id] != 0 &&  cat[:parent_id] != nil
        @first_level.each do |fl|
          if fl[:id] == cat[:parent_id]
            fl[:subcategories].push(id: cat[:id], name: cat[:name])
          end
        end
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @first_level }
    end
  end

  def how_it_works
  	@offer = Offer.new(max_price: 2500, min_price: 1000, max_people: 20, min_people: 6)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_intro_section.html.erb
<section id="intro" class="row">

		<article class="six columns">

			<h1><%= t 'hp.h1' %></h1> 
				<br><h2><%= t 'hp.h2' %></h2>

			<div class="call_to_action row">

				<span class="six columns ">
					<%= link_to (t('hp.links.browse_offers')), explore_path, id:'browse_offers_button', :class => 'blue radius nice button ' %>
				</span>

				<span class="six columns ">
					<%= link_to (t('hp.links.create_offer')), new_offer_path, id:'create_offers_button', :class => 'green radius nice button ' %>
				</span>
			<div>
		</article>

		<div class="video_container six columns last">
			<div class="vendor">
	        	<iframe width="560" height="315" src="http://www.youtube.com/embed/zFqPAZ4rpxU?rel=0&wmode=opaque" frameborder="0" allowfullscreen></iframe>
	        	</iframe>
        	</div>
		</div>
</section>



<script>
  $(document).ready(function(){
    // Target your .container, .wrapper, .post, etc.
    $(".video_container").fitVids();
  });
</script>

app/views/home/_testimonials.html.erb
<br><br><br><br><br><h1 id="who" >Who's Using MPPL?</h1><br>

<section id="testimonials" class="row">

		<article class="four columns">

			<h1>Israel Ruby on Rails Course</h1>

			<p><i>"We can't imagine what it would be like to compete with the giant course schools without MPPL. It simply allows us to sell our courses at such competitve prices and successfully sell courses against all odds even though we are a very small operation."</i> Elan Perach</p>

			<%= link_to "Visit Website", "http://rorcourse.blogspot.co.il/", class: "small blue button radius" %>

		</article>

		<article class="four columns">

			<h1>Taste Shop Raanana</h1>

			<p><i>"Since we were allready using other group buying systems moving to MPPL was a breeze. It is such a pleasure to be able to give our clients substantial discounts in a fair way that veryone pays the same at the end."</i></p>

			<%= link_to "Visit Website", "http://taste-shop.co.il/", class: "small blue button radius" %>

		</article>

		<article class="four columns">

			<h1>Mobile Web Course</h1>

			<p><i>"I have been teaching at one of the largest high tech schools for many years and could never imagine a way of become indepndant of them until I heard of MPPL. Now I can offer my top quality courses at such competitve prices that people think twice before signing up with the big names just because they have a name. In these hard financial times tools like this are in great need."</i> Ynon Perek</p>

			<%= link_to "Visit Website", "http://html5mobilecourse.blogspot.co.il/", class: "small blue button radius" %>

		</article>

</section>

app/views/home/_tour.html.erb
<!-- Home Tour -->
<ol id="joyRideTipContent">
  <li data-id="logo" data-text="What makes it so Fair?!" ><h3>is a Fair Way to Buy and Sell Group Offers</h3></li>

  <li data-id="logo" data-text="What Are These Group Offers You Speak of?" data-options="tipLocation:top;tipAnimation:fade"><h4>Well...</h4>1. For starters the more people that buy a group offer, the less everyone pays.<br/>2. You can determine the maximum price you are willing to pay.</li>

  <li data-id="days-left" data-text="OK...SO? Then What...?" data-options="tipLocation:top;tipAnimation:fade"><h4>These Are Group Offers!</h4>and each one consists of: <br/>1. A decreasing price range<br/>2. A min/max sale limit<br/>3. A Payment Date<br/></li>

  <li data-id="days-left" data-text="Thats What I'm Talking About! Sign Me Up." data-options="tipLocation:top;tipAnimation:fade"><h4>Then, You Pledge</h4>Meaning you preapprove a payment to buy something if enough people are willing to buy it with you, And if your lucky you may end up paying even less than the price you pledged</li>

  <li data-id="sign-up" data-options="tipLocation:top" data-text="Close" ><h5>What Are You Waiting For?</h5></li>

</ol>

app/views/home/about.html.erb
<div class= "row">

	<div class= "three columns">
	<%= image_tag ("http://i.istockimg.com/file_thumbview_approve/19354210/2/stock-illustration-19354210-teamwork.jpg") %>
	</div>
	<div class="nine columns">
		<h1><%= t 'about.h1' %></h1>
		<p>
		<i><%= t 'about.p1' %></i><br>
		<br><%= t 'about.p2' %><br>
		<br><%= t 'about.p3' %><br>
		<br><%= t 'about.p4' %><br>
		<br><%= t 'about.p5' %><br>
		</p>

	<br><br>

<!-- AddThis Follow BEGIN -->
<p><%= t 'about.follow_us' %></p>
<div class="addthis_toolbox addthis_32x32_style addthis_default_style">
<a class="addthis_button_facebook_follow" addthis:userid="morepeoplepayless"></a>
<a class="addthis_button_twitter_follow" addthis:userid="mpplcom"></a>
<a class="addthis_button_google_follow" addthis:userid="u/0/b/114342850935879496751/114342850935879496751/posts/p/pub"></a>
<a class="addthis_button_youtube_follow" addthis:userid="morepeoplepayless"></a>
<a class="addthis_button_pinterest_follow" addthis:userid="mpplcom"></a>
<a class="addthis_button_tumblr_follow" addthis:userid="morepeoplepayless"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=elanperach"></script>
<!-- AddThis Follow END -->

	</div>
</div>

app/views/home/explore.html.erb
<ul>

  <%@first_level.each do |fl|%>
    <li>
      <%= link_to fl[:name], category_path(fl[:id])%>
        <%fl[:subcategories].each do |sc|%>
          <ul>
            <li>
              <%= link_to sc[:name], category_path(sc[:id])%>
            </li>
          </ul>
        <%end%> 
    </li>
      
  <%end%>

</ul>
 

<%= render partial: "offers/offer_box" , :locals => { :all_offers => @all_offers } %>

app/views/home/faq.html.erb
	<div class="container">
		<div class="row">

				<h1><%= t 'faq.h1' %></h1>
				<section class="faq-section">

				<section class="faq-section">
				    <input type="checkbox" id="q1">
				    <label for="q1"><%= t 'faq.q1' %></label>
						<p><%= t 'faq.q1_answer' %></p>
				</section>

				<section>
				    <input type="checkbox" id="q2">
				    <label for="q2"><%= t 'faq.q2' %></label>
						<p><%= t 'faq.q2_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q3">
				    <label for="q3"><%= t 'faq.q3' %></label>
						<p><%= t 'faq.q3_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q4">
				    <label for="q4"><%= t 'faq.q4' %></label>
						<p><%= t 'faq.q4_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q5">
				    <label for="q5"><%= t 'faq.q5' %></label>
						<p><%= t 'faq.q5_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q6">
				    <label for="q6"><%= t 'faq.q6' %></label>
						<p><%= t 'faq.q6_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q7">
				    <label for="q7"><%= t 'faq.q7' %></label>
						<p><%= t 'faq.q7_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q8">
				    <label for="q8"><%= t 'faq.q8' %></label>
						<p><%= t 'faq.q8_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q9">
				    <label for="q9"><%= t 'faq.q9' %></label>
						<p><%= t 'faq.q9_answer' %></p>
				</section>

				<section class="faq-section">
				    <input type="checkbox" id="q10">
				    <label for="q10"><%= t 'faq.q10' %></label>
						<p><%= t 'faq.q10_answer' %></p>
				</section>


		</div>

</div>

app/views/home/how_it_works.html.erb
    <div class="row">

        <div class= "three columns">
          <%= image_tag ("http://i.istockimg.com/file_thumbview_approve/19394806/2/stock-illustration-19394806-business-team-people-icon-web.jpg") %>
        </div>

      <div class="nine columns">
        <h1><%= t 'how_it_works.title' %></h1>
        <section class="faq-section">
          <input type="checkbox" id="q1">
          <label for="q1"><%= t 'how_it_works.q1' %></label>
          	<p><%= t 'how_it_works.q1_answer_a' %></p>
          	<p><%= t 'how_it_works.q1_answer_b' %></p>
            <p><%= t 'how_it_works.q1_answer_c' %></p>
            <p><%= t 'how_it_works.q1_answer_d' %></p>
            <p><%= t 'how_it_works.q1_answer_e' %></p>
            <p><%= t 'how_it_works.q1_answer_f' %></p>
            <p><i><%= t 'how_it_works.q1_answer_g' %></i></p>

             <%= render "common/chart" %>

        <section class="faq-section">
          <input type="checkbox" id="q2">
          <label for="q2"><%= t 'how_it_works.q2' %></label>
            <p><%= t 'how_it_works.q2_answer_a' %></p>
            <p><i><%= t 'how_it_works.q2_answer_b' %></i></p>
        </section>

        <section class="faq-section">
          <input type="checkbox" id="q3">
          <label for="q3"><%= t 'how_it_works.q3' %></label>
            <p><%= t 'how_it_works.q3_answer_a' %></p>
            <p><%= t 'how_it_works.q3_answer_b' %></p>
            <p><%= t 'how_it_works.q3_answer_c' %></p>
            <p><%= t 'how_it_works.q3_answer_d' %></p>
            <p><%= t 'how_it_works.q3_answer_e' %></p>
            <p><%= t 'how_it_works.q3_answer_f' %></p>
            <p><%= t 'how_it_works.q3_answer_g' %></p>
            <p><%= t 'how_it_works.q3_answer_h' %></p>
            <p><%= t 'how_it_works.q3_answer_i' %></p>
            <p><%= t 'how_it_works.q3_answer_j' %></p>
            <p><%= t 'how_it_works.q3_answer_k' %></p>
            <p><%= t 'how_it_works.q3_answer_l' %></p>
        </section>

    </div>
  </div>

app/views/home/index.html.erb
<!-- render partial: "offers/offer_box" %> -->

<%= render partial: "intro_section" %>
<!--   %= render partial: "testimonials" % -->

app/views/home/privacy-policy.html.erb
<div class="row">

	<h2>MorePeoplePayLess.com Privacy Policy</h2>

			<p>
			We respect your right to privacy. We will never give your name or any personal information to third parties. PayPal Adaptive Payments will process all of the transactions on MorePeoplePayLess, so nobody will see your credit card information, besides PayPal.
			</p>

			<br><h3>Email</h3><p>
			We want to send you email offers and newsletters only if you want to receive them. We will send you email relating to your personal transactions, so you can keep a record, but we will keep these to a minimum.
			</p>


			<br><h3>Technology / Security</h3><p>
			MorePeoplePayLess uses cookies to help (anonymously) recognize you as a repeat visitor and to track traffic patterns on our site. We use this information to make MorePeoplePayLess more user-friendly, but that’s it.
			MorePeoplePayLess may obtain IP addresses from users. We will use this information to monitor and prevent fraud, diagnose problems, and (anonymously) estimate demographic information.
			<br>
			We use a variety of security measures, including encryption and authentication tools, to maintain the confidentiality of your personal information. Your personal information is stored behind firewalls and is only accessible by a limited number of people who are required to keep the information confidential.</p>


			<br>
			<h3>Offer Creators</h3><p>
			By entering into our User Agreement, MorePeoplePayLess Offer Creators agree to not abuse other users' personal information. Abuse is defined as using personal information for any purpose other than those explicitly specified in the Offer Creator’s Offer, or is not related to fulfilling delivery of a product or service explicitly specified in the Offer Creator’s Offer.
			<br>
			MorePeoplePayLess Offer Creators never receive users' credit card information.</p>


			<br>
			<h3>Wrap-up</h3><p>
			MorePeoplePayLess reserves the right to update this privacy policy at anytime. Updates to our privacy policy will be sent to the email address that you have provided us or posted prominently on the website.
			We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights, or in the good-faith belief that such action is necessary to comply with state and federal laws (such as U.S. Copyright Law).
			People under 18 are not permitted to use MorePeoplePayLess on their own, and so this privacy policy makes no provision for their use of the site.</p>

			<br>
			<h3>Questions</h3><p>
			If you have questions or suggestions you can contact us at: <a href="mailto:support@morepeoplepayless.com">support@morepeoplepayless.com</a></p>
</div>