config/routes.rb
MPPL::Application.routes.draw do

  
  post "paypal/pledge"

  get "paypal/redirect_to_paypal"
  
  scope "(:locale)", :locale => /en|he|it/ do
  
    resources :widgets do
      collection do
        get :translations
        get :faq
      end

      member do
        get :preview
        get :embed
        get :widget
        get :snippet
        get :snippet_mobile_portrait #320x240
        get :snippet_mobile_landscape #480x320
        get :snippet_small_tablet_portrait #600x800
        get :snippet_small_tablet_landscape #800x600
        get :snippet_tablet_portrait #768x1024
        get :snipppet_tablet_landscape #(1024x768)
      end
    end
    resources :categories
    resources :payment_notifications
    
      resources :offers do
  	    resources :pledges do
          member do
            post :pay
            get :paypal_details
          end
        end 
        resources :payments
  
        collection do
          get :chart
        end
        member do
          get :chart
          get :thankyou
          get :accept_cash
          post :receive_cash
          post :add_follower
          post :remove_follower
          post :contact_us
        end
      end
    
  end
  
  

  match '/:locale' => 'home#index'
  root :to => "home#index"


  
  
  scope "(:locale)", :locale => /en|he|it/ do devise_for :users 
  resources :users, :only => [:show, :index] 
   
  
  match 'my_offers', to: "offers#my", as: :my_offers
  match 'my_pledges', to: "pledges#my", as: :my_pledges

  match 'explore', to: "home#explore", as: :explore

  match 'faq', to: "home#faq", as: :faq

  match 'about', to: "payment_notifications#create", via: :post, as: :old_ipn_listener
  match 'about', to: "home#about", via: :get, as: :about

  match 'privacy', to: "home#privacy-policy", as: :privacy
  match 'terms', to: "home#terms-of-use", as: :terms
  match 'how-it-works', to: "home#how_it_works", as: :how_it_works

  match 'pledges', to: "pledges#all", as: :pledges_all
  match 'payments', to: "payments#all", as: :payments_all

  match 'preapproval_return/:id(/:old_pledge_id)', to: "pledges#preapproval_return", via: :get, as: :preapproval_return
  match 'preapproval_cancel/:id(/:old_pledge_id)', to: "pledges#preapproval_cancel", via: :get, as: :preapproval_cancel
  
  end


end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  before_filter :prepare_data, except: [:faq, :translations]
  
  
  def show
  end

  def preview
    render layout: false
  end

  def embed
    @container_id = params[:container_id]
  end


  
  def details
  end

  def faq
    render layout: false
  end

  def translations
    respond_to do |format|
      format.js 
    end
  end

  def snippet width=nil, height=nil
    if width
      @viewport[:width] = width
    end
    if height
      @viewport[:height] = height
    end

    render partial: "snippet", layout: false, content_type: 'text/plain'
  end

  def snippet_mobile_portrait #320x480
    snippet(320, 480)
  end
  def snippet_mobile_landscape #480x320
    snippet(480, 320)
  end
  def snippet_small_tablet_portrait #600x800
    snippet(600, 800)
  end
  def snippet_small_tablet_landscape #800x600
    snippet(800, 600)
  end
  def snippet_tablet_portrait #768x1024
    snippet(768, 1024)
  end
  def snipppet_tablet_landscape #(1024x768)
    snippet(1024, 768)
  end

  private 
  def prepare_data
    offer_id = params[:id]
    if(params[:locale])
      @locale = params[:locale]
    else
      @locale = "en"
    end

    @offer = Offer.find(offer_id)
    @pledge = Pledge.new
    @contact_form = ContactForm.new
    
    @price_values = @offer.price_steps
    @income = can?(:manage, :all) ? @offer.income : []
    @max_income = @offer.income_max
    @min_income = @offer.income_min

    @viewport = {
      width: (params[:width] ? params[:width] : 480),
      height: (params[:height] ? params[:height] : 720)
    }

  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
	
	TYPES = {
	 
		blogger: [680, 750],
		# mobile_portrait: [320, 480],
		# mobile_landscape: [480, 320],
		# small_tablet_portrait: [600, 800],
		# small_tablet_landscape:[800, 600],
		# tablet_portrait: [768, 1024],
		# tablet_landscape: [1024, 768],
		# desktop: [1680, 1050]
  }

	def snippet type = :blogger
		dimensions = WidgetsHelper::TYPES[type]
		width = dimensions[0]
		height = dimensions[1]
		render partial: "widgets/snippet", locals: { width: width, height: height }
	end
end

app/views/widgets/_faq_sheet.html.erb
<style type="text/css">

.faq-section {
  text-align:<%= @textalign %>;
  direction: <%= (@locale.in? ['he', 'ar']) ? 'rtl' : 'ltr' %>;
  margin: 20px;
}

</style>

<section class="faq-section">
<h1 style="padding-bottom:10px;"><%= t 'faq.h1' %></h1>
        <section>
            <input type="checkbox" id="q1">
            <label for="q1"><%= t 'widget.faq.q1' %></label>
            <p><%= t 'widget.faq.q1_answer' %></p>
        </section>

        <section>
          <input type="checkbox" id="q2">
            <label for="q2"><%= t 'widget.faq.q2' %></label>
            <p><%= t 'widget.faq.q2_answer_a' %></p>
            <p><%= t 'widget.faq.q2_answer_b' %></p>
        </section>

        <section>
          <input type="checkbox" id="q3">
            <label for="q3"><%= t 'widget.faq.q3' %></label>
            <p><%= t 'widget.faq.q3_answer_a' %></p>
            <p><%= t 'widget.faq.q3_answer_b' %></p>
        </section>

        <section>
          <input type="checkbox" id="q4">
            <label for="q4"><%= t 'widget.faq.q4' %></label>
            <p><%= t 'widget.faq.q4_answer' %></p>
        </section>

        <section>
          <input type="checkbox" id="q5">
            <label for="q5"><%= t 'widget.faq.q5' %></label>
            <p><%= t 'widget.faq.q5_answer' %></p>
        </section>

</section>

app/views/widgets/_price_sheet.html.erb
<br>
<h1><%= t 'widget.h1' %></h1>
<h2><%= t 'widget.h2' %></h2>

<%= render "common/chart" %>

<div id="price_details">

  <div id="price_range">
  	 <h2><%= t 'widget.price.min_price' %>	<%= @offer.min_price %>&#8362; &nbsp;&nbsp;&nbsp;&nbsp;  <%= t 'widget.price.max_price' %> <%= @offer.max_price %>&#8362;</h2>
  </div>

  <br>

  <div id="pledge_now">
     
      <!-- form start -->
      <%= simple_form_for([@offer, @pledge], url: offer_pledges_url(@offer), html: { target: "_blank"}) do |f| %>

        <%= f.input :amount, label: t('widget.price.i_want_in') do %>
          <%= f.select :amount,  offer_price_options(@offer) %>
        <% end %>

        <%= f.button :submit, type: :image, src: MPPL.config.paypal_button_url, id: "paypal-widget", alt: "pledge now", value: nil %>
      <% end %>
      <!-- form end -->
      <h2><%= t ('widget.price.reg_with_paypal') %></h2>
      <span><%= t ('widget.price.pledge_explanation') %></span>
      <div id="terms">
        <%= t ('widget.terms.1'), payment_collection_date: @offer.payment_collection_date %><br>
        <%= t ('widget.terms.2') %><br>
        <%= t ('widget.terms.3') %>

        <br>
      </div>
  </div>

</div>

app/views/widgets/_snippet.html.erb
<% container_id = "mppl_widget_#{width}_#{height}_#{@offer.id}" %><div id='<%= container_id %>' ></div>
<script type="text/javascript" src="<%= "#{embed_widget_url(@offer, format: :js)}?container_id=#{container_id}&locale=#{@locale}&width=#{width}&height=#{height}" %>" ></script>

app/views/widgets/embed.js.erb
(function(){
	var container = document.getElementById("<%= @container_id %>");
	if(!container){ return; }
	
	var iframe = document.createElement("iframe");
	iframe.src = "<%= widget_url(@offer) %>?locale=<%= @locale %>&width=<%= @viewport[:width] %>&height=<%= @viewport[:height] %>";
	iframe.width = <%= @viewport[:width] %>;
	iframe.height = <%= @viewport[:height] %>;
	iframe.frameBorder = "0";
	iframe.scrolling = "yes";
	container.appendChild(iframe);
}())

app/views/widgets/faq.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= render "faq_sheet" %>

app/views/widgets/loader.js.erb
(function(){

var jquery_js = "<%= root_url %>jquery/jquery.min.js";
var jquery_ui = "<%= root_url %>jquery_ui/js/jquery-ui-1.8.22.custom.min.js";
var charts_js = "<%= root_url %>widgets/highcharts/highcharts.js";
var offers_js = "<%= root_url %>widgets/offers.js";
var paypal_js = "https://www.paypalobjects.com/js/external/dg.js";
//////////////////////////////////////////////////////////////////////////////////////

var widget_container_id = "mppl_widget";//'<%= @widget_container_id %>';

var widget_container = document.getElementById(widget_container_id);
if(widget_container){

	var urls = [paypal_js, offers_js, charts_js, jquery_ui];

	if(!probe_jquery()){
		urls.push(jquery_js);
	}

	var cb = function(){};
	render_widget_inline(widget_container_id);
	loadScripts(urls, cb);

	// ensure_jquery(function(){
	// 	loadScript(paypal_js, loadScripts());
	// 	loadScript(charts_js, function(){
	// 			render_widget_inline(widget_container_id);
	// 			$(function(){
	// 				loadScript(offers_js);	
	// 			});
      	
 //     });
	// });
	
} else {
	console.info("no container!!!");
}

///////////////////////////////////////////////////////////////////////////////////////

/* works with IE!!! */
function render_widget_inline(container_id){
	var widget_content = "<%= j render 'tabbed_widget_2' %>";// "<%= 'j render template:' + 'items/index_widget' %>" ;
	var container = $("#" + container_id);
	container.html(widget_content);
	console.info("<%= __FILE__ %>");
}

function ensure_jquery(cb){
	if(probe_jquery()){
		console.info("jQuery is already here!");
	}else{
		console.info("jQuery isn't here yet!");
		console.info("loading...");
		loadScript(jquery_js, function(){
			if(probe_jquery()){
				console.info("jQuery is already here!");
				cb();
			} else {
				console.info("failed!");
			}
		});
		
	}
}

function probe_jquery(){
	if(typeof $ != 'undefined' && $ == jQuery){
		return true;
	} else {
		return false;
	}
}

function loadScripts(urls, cb){

	var url = urls.pop();
	console.log("going to load " + url);
	if(url){
		loadScript(url, loadScripts(urls, cb));	
	} else {
		console.log("all scripts loaded");
		cb();
	}
}

function loadScript(url, cb){
	var script_tag = document.createElement('script');
  script_tag.setAttribute("type","text/javascript");
  script_tag.setAttribute("src", url);
  if (script_tag.readyState) {
    script_tag.onreadystatechange = function () { // For old versions of IE
        if (this.readyState == 'complete' || this.readyState == 'loaded') {
            cb();
        }
    };
  } else { // Other browsers
    script_tag.onload = cb;
  }
  // Try to find the head, otherwise default to the documentElement
  (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag);
}

})();

app/views/widgets/preview.html.erb
<style type="text/css">
	
	.widget_code {
		margin-top: 50px;
	}

</style>


<% WidgetsHelper::TYPES.each do |type| %>
<% type_name = type[0] %>
<hr>
<div>
	<div class="widget_preview">
		<p>before widget</p>
		<%= snippet type_name %>
		<p>after widget</p>
 	</div>

 	

	<div class="widget_code">
 		<textarea cols=80 rows=4 id="widget_code_textarea" dir="ltr">
 			<%= snippet type_name %>
 		</textarea>
 	</div>
</div>
<% end %>

app/views/widgets/show.html.erb
<script type="text/javascript" src="https://www.paypalobjects.com/js/external/dg.js"></script>


<div id="details">
	<div id="details_header">
	<h1><%= @offer.title %></h1>
	</div>

	<div id="chart">
		<%= render partial: "widgets/price_sheet" %>
	</div>
	   

</div>

<div id="pledge">
</div>

app/views/widgets/snippet.html.erb
<%= render "snippet" %>

app/views/widgets/translations.html.erb
<h1>Widgets#translations</h1>
<p>Find me in app/views/widgets/translations.html.erb</p>

app/views/widgets/translations.js.erb
<%= render "common/translations.js" %>

app/views/widgets/video.html.erb
<h1>Widgets#video</h1>
<p>Find me in app/views/widgets/video.html.erb</p>