config/routes.rb
MPPL::Application.routes.draw do

  
  post "paypal/pledge"

  get "paypal/redirect_to_paypal"
  
  scope "(:locale)", :locale => /en|he|it/ do
  
    resources :widgets do
      collection do
        get :translations
        get :faq
      end

      member do
        get :preview
        get :embed
        get :widget
        get :snippet
        get :snippet_mobile_portrait #320x240
        get :snippet_mobile_landscape #480x320
        get :snippet_small_tablet_portrait #600x800
        get :snippet_small_tablet_landscape #800x600
        get :snippet_tablet_portrait #768x1024
        get :snipppet_tablet_landscape #(1024x768)
      end
    end
    resources :categories
    resources :payment_notifications
    
      resources :offers do
  	    resources :pledges do
          member do
            post :pay
            get :paypal_details
          end
        end 
        resources :payments
  
        collection do
          get :chart
        end
        member do
          get :chart
          get :thankyou
          get :accept_cash
          post :receive_cash
          post :add_follower
          post :remove_follower
          post :contact_us
        end
      end
    
  end
  
  

  match '/:locale' => 'home#index'
  root :to => "home#index"


  
  
  scope "(:locale)", :locale => /en|he|it/ do devise_for :users 
  resources :users, :only => [:show, :index] 
   
  
  match 'my_offers', to: "offers#my", as: :my_offers
  match 'my_pledges', to: "pledges#my", as: :my_pledges

  match 'explore', to: "home#explore", as: :explore

  match 'faq', to: "home#faq", as: :faq

  match 'about', to: "payment_notifications#create", via: :post, as: :old_ipn_listener
  match 'about', to: "home#about", via: :get, as: :about

  match 'privacy', to: "home#privacy-policy", as: :privacy
  match 'terms', to: "home#terms-of-use", as: :terms
  match 'how-it-works', to: "home#how_it_works", as: :how_it_works

  match 'pledges', to: "pledges#all", as: :pledges_all
  match 'payments', to: "payments#all", as: :payments_all

  match 'preapproval_return/:id(/:old_pledge_id)', to: "pledges#preapproval_return", via: :get, as: :preapproval_return
  match 'preapproval_cancel/:id(/:old_pledge_id)', to: "pledges#preapproval_cancel", via: :get, as: :preapproval_cancel
  
  end


end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  protect_from_forgery :except => [:widget, :preview, :snippet, :embed, :contact_us]
  before_filter  :authenticate_user!, except: [:index, :thankyou, :widget, :preview, :embed, :snippet, :show, :chart, :contact_us]
  load_and_authorize_resource except: [:thankyou, :widget,  :preview, :snippet, :embed, :contact_us, :chart]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.published
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  def my
    @offers = current_user.offers
    render action: :index
  end

  def thankyou
    @offer = Offer.find(params[:id])
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    offer_id = params[:id]
    user_id = current_user.try(:id)

    @offer = Offer.find(offer_id)
    @pledge = Pledge.new
    @following = Following.find_by_offer_and_user @offer, current_user
    @title = @offer.title
    # @category = @offer.category.name.to_s

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  

  def chart
    if params[:id]
      @offer = Offer.find(params[:id]) 
    else
      @offer = Offer.new
    end
    
    @offer.attributes = params[:offer]

    render template: "offers/chart_data.json", content_type: "application/json"
  end


  def preview
   widget
  end

  def snippet
    prepare_data
    render layout: false, content_type: 'text/plain'
  end

  def embed
    prepare_data
  end

  def widget
    prepare_data
    layout :widgets
  end


  def contact_us
    @contact_form = ContactForm.new params[:contact_form]
    @offer = Offer.find(params[:id])

    NotificationMailer.widget_contact_us(@contact_form, @offer).deliver

    respond_to do |format|
      format.json { render json: { success: true } }
      format.js { render nothing: true }
    end

  end


  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    @offer.max_price = 3500
    @offer.min_price = 2500
    @offer.max_people = 20
    @offer.min_people = 10

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])
    @offer.user_id = current_user.id

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])
    if params[:commit] == 'Follow'
      @offer.followers << current_user
    end
    if params[:commit] == 'Publish'
      @offer.published = true
      if(@offer.save)
        redirect_to :back, notice: "Successfully published!"
        return
      end
    end

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end


  #Offer owner only allowed
  #New action
  def accept_cash

    @offer = Offer.find(params[:id])

    if(@offer.accepting_cash?)

      @pledge = Pledge.new

      #display accept-cash form
      # form action => POST receive_cash
      #the form should include:
      #cash amount
      #buyer details(email!, name, etc.)

    else
      #redirect to @offer#show with notice/warning

      redirect_to @offer, notice: "Can't accept cash " + (@offer.available_pledges.count == @offer.max_people ? "any more" : "yet")
    end
  end

  #Offer owner only allowed
  #Create Action
  def receive_cash
    
    @offer = Offer.find(params[:id])
    @pledge = @offer.pledges.new(params[:pledge])
    @pledge.payment_status = :cash

    if(!@offer.receiving_cash?)
      redirect_to @offer, notice: "Can't accept cash " + (@offer.available_pledges.count == @offer.max_people ? "any more" : "yet")
    else
      #check email
      email = params[:user][:email]
      buyer = User.find_by_email email

      if(!buyer)
        password = KeePass::Password.generate('h{8}')
        name = params[:user][:name]
        begin
        buyer = User.create!(name: name, email: email, password: password, password_confirmation: password)
        rescue
          Rails.logger.error("failed to create a user: #{params.inspect}")
          render nothing: true
          return   
        end
        @pledge.user = buyer
        pledge = @pledge
        NotificationMailer.account_creation(buyer, password).deliver
      end

      @pledge.user = buyer
      pledge = @pledge
      if !@pledge.save
        #redirect_to :back, alert: pledge.errors.full_messages.join("<br>")
        render action: :accept_cash
      else
        redirect_to offer_pledges_path @offer
        NotificationMailer.successful_pledge_buyer(pledge).deliver
      end #if 2
    end #if 1

  end #def



  def add_follower

    @offer = Offer.find(params[:id])
    current_user.try(:follow, @offer)
    @following = Following.find_by_offer_and_user(@offer, current_user)

    respond_to do |format|
      format.html { redirect_to @offer, notice: 'You are now following this offer' }
      format.js
    end
  end

  def remove_follower

    offer = Offer.find params[:id]

    user = current_user

    user.unfollow offer

    respond_to do |format|
      format.html { redirect_to @offer, notice: 'You are no longer following this offer' }
      format.js
    end

  end

  private 
  def prepare_data
    offer_id = params[:id]
    if(params[:locale])
      @locale = params[:locale]
    else
      @locale = "en"
    end

    @offer = Offer.find(offer_id)
    @pledge = Pledge.new
    @contact_form = ContactForm.new
    @viewport = {
      width: 480,
      height: 960
    }
    @price_values = @offer.price_steps
    @income = can?(:manage, :all) ? @offer.income : []
    @max_income = @offer.income_max
    @min_income = @offer.income_min
  end


end

app/helpers/offers_helper.rb
module OffersHelper

	SHEKEL_SIGN = "&#8362;"

	def percentage offer
		100 * offer.available_pledges.count.to_f/offer.max_people
	end

	def progress_color offer

		color = "orange"
		color = "grey"  if offer.available_pledges.count < offer.min_people
		color = "blue" if offer.status == Offer::STATUS_ACTIVE

		color

	end

	def unit offer

		case offer.currency
		when "ILS"
			SHEKEL_SIGN
		when "NIS"
			SHEKEL_SIGN
		when "USD"
			"$"
		else
			"$"
		end
	end

	#TODO: factor out to model db dependent code 
	def offer_price_options offer
		offer_next_pledge_price = offer.next_pledge_price
		offer.price_steps.select{|people, price| price <= offer_next_pledge_price }.map do |people, price|

			formatted_price = number_to_currency(price, unit: unit(offer), precision: 0)

			["#{formatted_price} - #{people} #{t('offer.show.people')}".html_safe, price]

		end
	end

	def offer_price_range offer
		max_price = number_to_currency(offer.max_price, unit: unit(offer))

    min_price = number_to_currency(offer.min_price, unit: unit(offer))

    "#{max_price}  &rarr; #{min_price}"
	end

  def offer_people_pledged offer
  	"#{offer.available_pledges.count}/#{offer.max_people}"
  end
end

app/views/offers/_form.html.erb
<div class="row">
  <div class="eight columns">
    <%= simple_form_for @offer,
    {
      :html => { :class => 'form-horizontal nice' },
      :defaults => { :input_html => { :class => 'input-text offer-form' }, :label_html => { :id => 'offer-form' } }
    } do |f| %>
      <%= f.input :pioneer_discount, as: :hidden %>
      
      <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
      <%= f.input :title  %>
      <%= f.input :details, as: :text, input_html: { rows: 1 } %>
      <%= f.input :website %>
      <%= f.input :image_url %>
      <%= f.association :category, :include_blank => false %>
      <br><br>
      <div id="chart_editor">

        <div id="chart_editor_top">

          <div id="price_limits" >
            <%= f.input :max_price, label: "", input_html: {id: 'offer_max_price'} %>
            <br><br><br><br><b><b class="price_range">Price Range</b>
            <%= f.input :min_price, label: "", input_html: {id: 'offer_min_price'} %>
          </div>

          <div id="offer_form_chart_container">
            <%= render partial: "common/chart" %>
          </div>

        </div>

        <div id="chart_editor_bottom">
          <div id="people_limits">
            <%= f.input :min_people, label: "", input_html: {id: 'offer_min_people'} %>
            <%= f.input :max_people, label: "", input_html: {id: 'offer_max_people'} %>
          </div>
        </div>

      </div>
    </div>
      <div class="four columns">

      <%= f.input :payment_collection_date, as: :date_picker, 
                              input_html: {id: 'date_picker'}  %>
        <div class="form-actions">
          <% unless @offer.new_record? %>
            <% if @offer.published? %>
              <span>Published</span>
            <% else %>
              <%= f.button :submit, :class => 'btn-primary', value: 'Publish',
                            :confirm => 'Are you sure you are ready to publish your offer? Once it has been published you can not edit it. If you are ready click OK and our staff will check the offer for qaulity assurance.' %>
            <% end %>
          <% end %>
          <%= f.button :submit, :class => 'nice big radius green button' %>
        </div>
      </div>
    <% end %>
</div>


<script type="text/javascript">
  $(function(){
    var $form = $("form");
    $("input[type=number]").change(function(){
    
      var form_data = $form.serialize();
      console.info(form_data);
      var url = "<%= chart_offers_path %>";
      $.ajax(url, {
        data: form_data,
        dataType: "json",
        success: function(chart_data){
          
          console.info(chart_data);
          var chart = $.mppl_chart;
          
          var price_series = chart.get("price");
          if(price_series){
            price_series.setData(chart_data.price_steps);  
          }
          
          if(chart_data.income_steps){
            chart.get("income").setData(chart_data.income_steps);
          }

          chart.redraw();
          
        }
      });
      
    });
  });
</script>

app/views/offers/_offer_box.html.erb
<div id="offer_container" class="offers clearfix">
  <%
    @offers.each do |offer|
  %>
  <!-- Box -->

  <div class="box">

    <!-- Offer -->
    <div class="offer">

      <!-- Info -->
      <div class="info">
        <%= render partial: "masonry/offer_info", locals: { offer: offer } %>
      </div>

      <!-- Offer Image -->
      <div class="offer_image" >
        <%= image_tag offer.image_url, alt: offer.title, width: "280px" %>
      </div>

    </div><!-- Offer End -->
  </div><!-- box end -->
  <% end %>
</div><!-- Offer Collection End -->

app/views/offers/_paypal_pledge.html.erb
<%= simple_form_for([@offer, @pledge]) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :amount, include_blank: false, label: t('offer.show.choose_your_price') do %>
        <%= f.select :amount,  offer_price_options(@offer), id: "offer-show-select" %>
      <% end %>
    </div>

  <div class="form-actions" id="paypal-pledge-now">

    <%= f.button :submit, type: :image, src: MPPL.config.paypal_button_url, class: "btn paypal", alt: "pledge now", value: nil, id: "paypal_offer_show" %>
  </div>
  <% end %>

app/views/offers/_snippet.html.erb
<div id="mppl_widget_<%= @offer.id %>"></div>
<script type="text/javascript" src="<%= embed_offer_url(@offer, format: :js) + "?locale=#{@locale}" %>">
</script>

app/views/offers/_tabbed_widget_2.html.erb
<link rel="stylesheet" href="<%= root_url %>widgets/styles.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<%= root_url %>widgets/faq.css" type="text/css" media="screen" />
<style type="text/css">
	
</style>

<script>
	var price_values = <%= @offer.price_steps %>;
  var income = <%= (can? :manage, :all) ? @offer.income : [] %>;
  var max_income = <%= @offer.income_max %>;
  var min_income = <%= @offer.income_min %>;
  
  jQuery(document).ready(function($) { 

    var tabs = $(".mppl_widget_tab");

		var sheets = $(".mppl_widget_sheet");
		for(var i=0; i<tabs.length; i++){

			if(sheets[i]){
				var sheet = $(sheets[i]);
				tabs[i].sheet = sheet;
				sheet.hide();	
			} else {
				var sheet = { show: function(){}};
				tabs[i].sheet = sheet;
				
			}
		
		}

		if(navigator.appName == 'Microsoft Internet Explorer'){
			$('#widget_faq_tab a').attr('href', '<%= faq_url %>');
		}

		tabs.click(function(evt) {
			console.info({tab_clicked: evt});
			if(navigator.appName == 'Microsoft Internet Explorer'){
				if(this.id == 'widget_faq_tab'){
					return true;
				}
			}

			tabs.removeClass("selected");
			$(this).addClass("selected");

			sheets.hide();
     
      var sheet = ($(this)[0]).sheet;
			sheet.show();
			return false;
		});


		tabs[0].click();

	 });
</script>


<!--[if gte IE 6]>
<style type="text/css">

ul#navigation li.selected a:link, ul#navigation li.selected a:visited {
	filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#d1d1d1', endColorstr='#f2f2f2'); /* IE6,IE7 */
	-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#d1d1d1', endColorstr='#f2f2f2')"; /* IE8 */
}
</style>
<![endif]-->

<ul id="navigation">
	<li class="mppl_widget_tab"><a href="#"><%= t 'widget.price.tab' %></a></li>
	<li class="mppl_widget_tab"><a href="#"><%= t 'widget.contact.tab' %></a></li>
	<li class="mppl_widget_tab"><a href="#"><%= t 'widget.video.tab' %></a></li>
</ul>

<div class="content" style="position: relative;">

	<div class="widget_body">

		<div class="mppl_widget_sheet">
			<%= render "widgets/price_sheet" %>
		</div>


		<div class="mppl_widget_sheet">
			<%= render "widgets/contact_us_sheet" %>
		</div>

		<div class="mppl_widget_sheet">
			<%= render "widgets/video" %>
		</div>

	</div><!-- widget body -->


	<div id="widget_footer">
		<h2><%= link_to t('widget.powered_by_mppl'), root_url %></h2>
	</div>
</div>

app/views/offers/_tour.html.erb
<!-- Offer Tour -->
<!-- <ol id="offer-tour" style="display: none;">
  <li data-id="offer-title">
  	Surprise here! This is the title!
  </li>
  <li data-id="offers-pledges">Aready hooked dudes!</li>
  <li data-id="chart">Nice eh?!</li>
  <li data-id="sign-up">Don't forget to sign up!</li>
  <li data-id="offer-addthis-buttons">Tell other dudes!</li>
  <li data-id="pledge_amount">You'r da boss dude!</li>
</ol> -->

app/views/offers/_widget.js.erb
<style type="text/css">

</style>

<div>
 	<header>
 		<h1><%= link_to @offer.title, offer_url(@offer) %></h1>
    <%= @offer.details %>
 	</header>
 	<div>
 		<%= image_tag @offer.image_url %>
 		<div>
 			<dt class="has-tip tip-left" data-width="130" title="When you pledge no funds are transfered until the payment date.">Pledge Now</dt>
        <dd>
          <%= simple_form_for([@offer, @pledge], url: offer_pledges_url(@offer)) do |f| %>
            <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :amount, :collection => @offer.prices, include_blank: false, label: t("Choose Your Price") %>
          </div>

          <div class="form-actions">
          <% paypal_gif = "https://www.paypalobjects.com/en_US/i/bnr/bnr_MSPFbanner_ec2_143x32.gif" %>
            <%= f.button :submit, type: :image, src: paypal_gif, class: "btn paypal", alt: "pledge now", value: nil %>
          </div>
          <% end %>

        </dd>

 		</div>
 	</div>
</div>

app/views/offers/add_follower.js.erb
$("#follow_form").hide();
$("#unfollow_form").show();

app/views/offers/embed.js.erb
(function(){
	var container = document.getElementById("mppl_widget_<%= @offer.id %>");
	if(!container){ return; }
	var iframe = document.createElement("iframe");
	iframe.src = "<%= widget_offer_url(@offer) %>?locale=<%= @locale %>";
	iframe.width = <%= @viewport[:width] %>;
	iframe.height = <%= @viewport[:height] %>;
	iframe.frameBorder = "0";
	iframe.scrolling = "no";
	container.appendChild(iframe);
}())

app/views/offers/new.html.erb
<h1><%= t ('offer.new.h1')%></h1>
<%= render :partial => 'form' %>

app/views/offers/remove_follower.js.erb
$("#unfollow_form").hide();
$("#follow_form").show();

app/views/offers/snippet.html.erb
<%= render "snippet" %>

app/views/offers/thankyou.html.erb
<div class= "row">

  <div class= "three columns">
  <%= image_tag ("thank-you.jpg") %>
</div>
<div class="nine columns">

  <h1><%= t 'thankyou.title' %> <%= link_to @offer.title, offer_path(@offer) %></h1>

    <br>
    <h4><%= t 'thankyou.p1' %> <b><%= link_to t('thankyou.here'), my_pledges_url %></b>.</h4>
    </br>


    <p><%= t 'thankyou.spread_the_news' %></p>

    <%= link_to "FaceBook", 'https://www.facebook.com/sharer.php?u=' +
        offer_url(@offer) + '&t=' + @offer.title, target: :blank %> |
    <%= link_to "Twitter", 'http://twitter.com/home?status=' + ' I found a great offer - ' + @offer.title + ' The more people that buy the less everyone pays! ' + offer_url(@offer) + '#MPPL', target: :blank %> |
    <%= link_to "Google +", 'https://plus.google.com/share?url=' + offer_url(@offer), target: :blank %> |
    <%= link_to "Digg", 'http://digg.com/submit?url=' + offer_url(@offer), target: :blank %> |
    <%= link_to "StumbleUpon", 'http://www.stumbleupon.com/submit?url=' + offer_url(@offer) + '&title=' + @offer.title, target: :blank %> |
    <%= mail_to "friends@friends.com", 'Email', subject: "Hey Dude, I found this great offer you might like", body: "the cool thing is that if we can get more people to pledge for the offer the price keeps going down. Are you in?", target: :blank %>

    <br>
    <br>

    <h3><%= t'thankyou.start_an_offer' %></h3>


    <h1><%= link_to t('hp.links.create_offer'), new_offer_path, class: "nice radius large button" %> </h1>

</div>
</div>